### ISSUE TITLE
team name field styles blend into background

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/dashboard-ui-plan-funnel#3]
![screen shot 2017-07-01 at 9 18 57 am](https://user-images.githubusercontent.com/313947/27763320-d8016072-5e3e-11e7-8e1f-897c972ef052.png)

**Comment by Tolmark12** [comment]
Fixed / Deployed - `bower update plan-funnel`

**Comment by jedgalbraith** [comment]
updated, but no diff. I'm on `nanobox-dash-ui-plan-funnel#63211e31d5`

![screen shot 2017-07-01 at 9 15 46 pm](https://user-images.githubusercontent.com/313947/27766994-8b353fac-5ea2-11e7-82b4-1b26d3ae79bf.png)

**Comment by Tolmark12** [comment]
Oh, I misunderstood what the issue is, it looks like the background has lost the white.
